<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HistoryOfIndividualRecordSeeder extends Seeder
{
    public function run(): void
    {
        $faker = Faker::create();

        $records =
        [
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '44 F. Ocampo',
                'mother_last_name' => 'Von Wensierski',
                'mother_first_name' => 'Rimelda',
                'child_last_name' => 'Von Wensierski',
                'child_first_name' => 'Sophia',
                'sex' => 'Female',
                'birthdate' => '2023-10-20',
                'height'  => '57.2',
                'weight'  => '4.4',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Villanueva Comp.',
                'mother_last_name' => 'Celso',
                'mother_first_name' => 'Cheryll',
                'child_last_name' => 'Celso',
                'child_first_name' => 'Ethan Rheyl',
                'sex' => 'Male',
                'birthdate' => '2023-11-25',
                'height'  => '44.1',
                'weight'  => '6.7',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '366 Atis St. Man. 4B',
                'mother_last_name' => 'Artates',
                'mother_first_name' => 'Hazel',
                'child_last_name' => 'Artates',
                'child_first_name' => 'Aaliyah Jayne',
                'sex' => 'Female',
                'birthdate' => '2023-09-21',
                'height'  => '62.5',
                'weight'  => '8.2',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '12 Uranium',
                'mother_last_name' => 'Erlano',
                'mother_first_name' => 'Sharmaine',
                'child_last_name' => 'Erlano',
                'child_first_name' => 'Aaron Matthew',
                'sex' => 'Male',
                'birthdate' => '2023-03-18',
                'height'  => '80.2',
                'weight'  => '7.9',
            ],
                [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '24 Atis St. Verdant',
                'mother_last_name' => 'Villanueva',
                'mother_first_name' => 'Divina',
                'child_last_name' => 'Villanueva',
                'child_first_name' => 'Aaron Sach',
                'sex' => 'Male',
                'birthdate' => '2023-01-08',
                'height'  => '70.2',
                'weight'  => '6.9',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '10 Silver',
                'mother_last_name' => 'Madcasim',
                'mother_first_name' => 'Jeham',
                'child_last_name' => 'Nadcasim',
                'child_first_name' => 'Abdul Mojib',
                'sex' => 'Male',
                'birthdate' => '2023-04-20',
                'height'  => '65.5',
                'weight'  => '5.7',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '3 Silver Camela 4A',
                'mother_last_name' => 'Guila',
                'mother_first_name' => 'Claudet',
                'child_last_name' => 'Guilo',
                'child_first_name' => 'Abegail',
                'sex' => 'Female',
                'birthdate' => '2023-08-03',
                'height'  => '57.2',
                'weight'  => '4.4',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '18 Ubas Verdant',
                'mother_last_name' => 'Celiz',
                'mother_first_name' => 'Angela',
                'child_last_name' => 'Celiz',
                'child_first_name' => 'Abigeil',
                'sex' => 'Female',
                'birthdate' => '2023-12-22',
                'height'  => '70.2',
                'weight'  => '6.9',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Thelma Villa Cristina',
                'mother_last_name' => 'Apog',
                'mother_first_name' => 'Bernadette',
                'child_last_name' => 'Belando',
                'child_first_name' => 'Abriana Brielle',
                'sex' => 'Female',
                'birthdate' => '2023-11-05',
                'height'  => '44.1',
                'weight'  => '6.7',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Greenview',
                'mother_last_name' => 'Pineda',
                'mother_first_name' => 'Athena',
                'child_last_name' => 'Pineda',
                'child_first_name' => 'Abrianah',
                'sex' => 'Female',
                'birthdate' => '2023-11-12',
                'height'  => '62.5',
                'weight'  => '8.2',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Hernandez',
                'mother_last_name' => 'Bacatan',
                'mother_first_name' => 'Keithlin',
                'child_last_name' => 'Bacatan',
                'child_first_name' => 'Acashia Faith',
                'sex' => 'Female',
                'birthdate' => '2023-08-01',
                'height'  => '57.2',
                'weight'  => '4.4',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Monique',
                'mother_last_name' => 'Jeniebre',
                'mother_first_name' => 'Chabelita',
                'child_last_name' => 'Beron',
                'child_first_name' => 'Ace Caleb',
                'sex' => 'Male',
                'birthdate' => '2023-10-24',
                'height'  => '44.1',
                'weight'  => '6.7',
            ],
                [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '50 Molave St. Manuela',
                'mother_last_name' => 'Doumbo',
                'mother_first_name' => 'Aira',
                'child_last_name' => 'Doumbo',
                'child_first_name' => 'Ace',
                'sex' => 'Male',
                'birthdate' => '2023-10-12',
                'height'  => '80.2',
                'weight'  => '7.9',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '15 Saging',
                'mother_last_name' => 'Beron',
                'mother_first_name' => 'Chabelita',
                'child_last_name' => 'Beron',
                'child_first_name' => 'Ace Kaleb',
                'sex' => 'Male',
                'birthdate' => '2023-10-24',
                'height'  => '44.1',
                'weight'  => '6.7',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Hernandez',
                'mother_last_name' => 'Azusenas',
                'mother_first_name' => 'Ara Mae',
                'child_last_name' => 'Quimbo',
                'child_first_name' => 'Ace',
                'sex' => 'Male',
                'birthdate' => '2023-10-12',
                'height'  => '70.2',
                'weight'  => '6.9',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '25 Guio',
                'mother_last_name' => 'Miraflor',
                'mother_first_name' => 'Marjorie',
                'child_last_name' => 'Miraflor',
                'child_first_name' => 'Acer Jacob',
                'sex' => 'Male',
                'birthdate' => '2023-12-04',
                'height'  => '62.5',
                'weight'  => '8.2',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Batibot',
                'mother_last_name' => 'Palwa',
                'mother_first_name' => 'Lharamel',
                'child_last_name' => 'Doctor',
                'child_first_name' => 'Acevone Lucas',
                'sex' => 'Male',
                'birthdate' => '2023-09-11',
                'height'  => '57.2',
                'weight'  => '4.4',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '45 Kasoy St',
                'mother_last_name' => 'Saberano',
                'mother_first_name' => 'Krystel Jay',
                'child_last_name' => 'Saberano',
                'child_first_name' => 'Ada Yrza',
                'sex' => 'Female',
                'birthdate' => '2023-10-17',
                'height'  => '80.2',
                'weight'  => '7.9',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => 'Adelfa St. DMS',
                'mother_last_name' => 'Belardo',
                'mother_first_name' => 'Princess',
                'child_last_name' => 'Belardo',
                'child_first_name' => 'Adam',
                'sex' => 'Male',
                'birthdate' => '2023-04-10',
                'height'  => '80.2',
                'weight'  => '7.9',
            ],
            [
                'child_number' => $childNumber = $faker->numberBetween(100, 999),
                'address' => '254 Atis Manuela',
                'mother_last_name' => 'Castañaday',
                'mother_first_name' => 'Marivic',
                'child_last_name' => 'Castañaday',
                'child_first_name' => 'Adam Gian',
                'sex' => 'Male',
                'birthdate' => '2023-12-14',
                'height'  => '44.1',
                'weight'  => '6.7',
            ],
        ];

        $commonData =
        [
            'ip_group' => 'No',
            'created_at' => NOW(),
            'updated_at' => NOW()
        ];

        foreach ($records as $record)
        {
            $data = array_merge($commonData, $record);
            DB::table('individual_records')->insert($data);
        }
    }
}